### ISSUE TITLE
Licenceless creation fails

### ISSUE THREAD

**Issue by emanueljg** [jpakkane/msicreator#12]
Creating an msi without a license fails on `createmsi.py:197` with this error:
`NameError: name 'product' is not defined`

**Comment by jpakkane** [comment]
For WiX 4 (current trunk) this is a known issue. They have changed the XML syntax and I could not make it work again with the time & resources I had. Patches welcome.

**Comment by emanueljg** [comment]
> For WiX 4 (current trunk) this is a known issue. They have changed the XML syntax and I could not make it work again with the time & resources I had. Patches welcome.

I see. I have another question but I'll be proper and open a new issue for it.
