### ISSUE TITLE
Creating empty directory.

### ISSUE THREAD

**Issue by mikkeljohnsen** [jpakkane/msicreator#2]
Your script is creating and entry for a Directory. ex:

<Directory Id="framework_etc_dbus-1_system.d" Name="system.d"/>

Bu the "wixl" tool is not creating it (when installing). Do MS WiX tool do that ?

**Comment by jpakkane** [comment]
I don't understand the question here. Can you be more specific?

The staging directory is not part of the install as discussed in the readme. If you have a file `staging_dir/prog.exe` it will get installed to `c:\program files\Progname\prog.exe`.

**Comment by mikkeljohnsen** [comment]
Yes but if I have "staging/tempdir/" it will not get installed in "c:\Program Files\Progname\tempdir".
My question is, is that working on Windows or is a "wixl" problem.

**Comment by jpakkane** [comment]
WiX behaves the same. I don't know how you would create an empty dir apart from having a dummy file in it. MSI seems to work based on files, not directories.

**Comment by mikkeljohnsen** [comment]
That is how I do it now, with a dummy file.
WiX should add that feature.
