### ISSUE TITLE
Create Registry entries

### ISSUE THREAD

**Issue by mikkeljohnsen** [jpakkane/msicreator#5]
Is it possible to make registry entries ?

**Comment by jpakkane** [comment]
No. Patches welcome.

**Comment by djdany01** [comment]
Can you provide any use cases for this? I can try to implement it.

**Comment by Djdany95** [comment]
@mikkeljohnsen Can you provide any use cases for this? I can try to implement it.

**Comment by jpakkane** [comment]
[This is actually possible now.](https://github.com/jpakkane/msicreator/commit/9955f2618cd693a5901e637e3801ed6fd6af34f1)
